M48
; DRILL file {KiCad (6.0.5)} date Thu Sep 15 17:30:39 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-09-15T17:30:39-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.5)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X4.35Y-2.2
X4.35Y-6.1
X5.95Y-2.2
X5.95Y-6.1
T0
M30
